In [1]:
import tensorflow as tf
import numpy as np

In [9]:
model = tf.saved_model.load('../model_zoo/TF/bert-base-uncased')
infer = model.signatures['serving_default']

In [4]:
model.serving.input_signature

({'token_type_ids': TensorSpec(shape=(None, None), dtype=tf.int32, name='token_type_ids'),
  'attention_mask': TensorSpec(shape=(None, None), dtype=tf.int32, name='attention_mask'),
  'input_ids': TensorSpec(shape=(None, None), dtype=tf.int32, name='input_ids')},)

In [21]:
from transformers import BertTokenizer

In [38]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
#model = TFGPT2Model.from_pretrained('bert-base-uncased')
text = "Paris is the [MASK] of France."
encoded_input = tokenizer(text, return_tensors='tf')


In [39]:
encoded_input

{'input_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=
array([[ 101, 3000, 2003, 1996,  103, 1997, 2605, 1012,  102]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [40]:
result = infer(input_ids=encoded_input['input_ids'],attention_mask=encoded_input['attention_mask'],token_type_ids=encoded_input['token_type_ids'])

In [47]:
p = np.asarray(result['pooler_output'])

In [50]:
tokenizer.decode(np.argmax(p))

'[ u n u s e d 2 8 5 ]'