In [1]:
import tensorflow as tf
import numpy as np
from transformers import TFBertModel

2022-12-09 19:19:04.738972: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-09 19:19:04.856932: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-12-09 19:19:04.856950: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-12-09 19:19:04.886631: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-12-09 19:19:05.641001: W tensorflow/stream_executor/platform/de

### Temp Code b/c I forgot to checkin the model_zoo (other laptop)

In [2]:
model = TFBertModel.from_pretrained('bert-base-uncased')
tf.saved_model.save(model,"./models/bert/")

Downloading: 100%|██████████| 570/570 [00:00<00:00, 689kB/s]
Downloading: 100%|██████████| 536M/536M [00:29<00:00, 18.1MB/s] 
2022-12-09 19:19:40.243605: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-12-09 19:19:40.245586: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2022-12-09 19:19:40.245614: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-25-33): /proc/driver/nvidia/version does not exist
2022-12-09 19:19:40.251581: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropria

INFO:tensorflow:Assets written to: ./models/bert/assets


INFO:tensorflow:Assets written to: ./models/bert/assets


In [9]:
model = tf.saved_model.load('../model_zoo/TF/bert-base-uncased')
infer = model.signatures['serving_default']

In [4]:
model.serving.input_signature

({'token_type_ids': TensorSpec(shape=(None, None), dtype=tf.int32, name='token_type_ids'),
  'attention_mask': TensorSpec(shape=(None, None), dtype=tf.int32, name='attention_mask'),
  'input_ids': TensorSpec(shape=(None, None), dtype=tf.int32, name='input_ids')},)

In [21]:
from transformers import BertTokenizer

In [38]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
#model = TFGPT2Model.from_pretrained('bert-base-uncased')
text = "Paris is the [MASK] of France."
encoded_input = tokenizer(text, return_tensors='tf')


In [39]:
encoded_input

{'input_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=
array([[ 101, 3000, 2003, 1996,  103, 1997, 2605, 1012,  102]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [40]:
result = infer(input_ids=encoded_input['input_ids'],attention_mask=encoded_input['attention_mask'],token_type_ids=encoded_input['token_type_ids'])

In [47]:
p = np.asarray(result['pooler_output'])

In [50]:
tokenizer.decode(np.argmax(p))

'[ u n u s e d 2 8 5 ]'